---

- hosts: mcs
  remote_user: root
  tasks: 

    - name: Disable dpkg fsync
      shell: echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/unsafe-io
      args: 
        creates: /etc/dpkg/dpkg.cfg.d/unsafe-io

    - name: Install dirmngr
      apt:
        name: dirmngr
        state: present

    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present

    - name: Upgrade debian
      apt:
        update_cache: true
        upgrade: true

    - name: Install required debs
      apt:
        name: "{{ item }}"
        state: present
      with_items: 
        - screen
        - openjdk-8-jre
        - aptitude
        - curl

    - name: Create /usr/local/minecraft
      file:
        path: /usr/local/minecraft
        recurse: yes
        state: directory

    - name: Download minecraft server
      get_url:
        url: https://launcher.mojang.com/mc/game/1.12.2/server/886945bfb2b978778c3a0288fd7fab09d315b25f/server.jar
        dest: /usr/local/minecraft/server.jar

    - name: Copy server.properties
      template:
        src: files/server.properties
        dest: /usr/local/minecraft/server.properties
      register: config

    - name: Copy eula.txt
      template: 
        src: files/eula.txt
        dest: /usr/local/minecraft/eula.txt

    - name: Install rc.local
      template:
        src: files/rc.local
        dest: /etc/rc.local
        mode: 755

    - name: Finally run rc.local
      command: /etc/rc.local
      